export const SET_USER = "SET_USER";
export const SET_ACCOUNTS = "SET_ACCOUNTS";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const ADD_TRANSACTIONS = "ADD_TRANSACTIONS";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
